//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquisoftApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachments
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public string FileSize { get; set; }
        public Nullable<int> ProjectId { get; set; }
    
        public virtual Projects Projects { get; set; }
    }
}
