//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquisoftApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budgets
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Comments { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> IdState { get; set; }
    
        public virtual Projects Projects { get; set; }
        public virtual State State { get; set; }
    }
}
