//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquisoftApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int IdClient { get; set; }
        public string Name { get; set; }
        public string Last_Name { get; set; }
        public string Direction { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> idState { get; set; }
    }
}
