//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquisoftApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArquisoftEntities : DbContext
    {
        public ArquisoftEntities()
            : base("name=ArquisoftEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<State> State { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Attachments> Attachments { get; set; }
        public virtual DbSet<Audit> Audit { get; set; }
        public virtual DbSet<Budgets> Budgets { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<ModuleOperations> ModuleOperations { get; set; }
        public virtual DbSet<Modules> Modules { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
        public virtual DbSet<RoleOperations> RoleOperations { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<VendorMaterials> VendorMaterials { get; set; }
        public virtual DbSet<BudgetLines> BudgetLines { get; set; }
        public virtual DbSet<Settings> Settings { get; set; }
    }
}
